permalink: /posts/:title
future: true
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
github: thehackerwithin
rdiscount:
  extensions: [smart]
url: http://thehackerwithin.github.com/swinburne
name: Hacker Within
chapter: Swinburne
description: An initial blog and site for THW at Swinburne
twitter: hackerwithin
gravatar_url: http://www.gravatar.com/avatar/0203c034a145af6cc2576d56cdb4cf73
disqus_username: hackerwithinadmin
